site_name: Poolshark Docs
# site_description: 'Directional liquidity for Ethereum.'
site_url: https://poolshark-protocol.github.io/docs/
repo_name: 'GitHub'
repo_url: 'https://github.com/poolshark-protocol/docs/'
edit_uri: 'tree/main/site/content'
copyright: 'Written by Poolshark Labs'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    # - name: 日本語
    #   link: ./ja/
    #   lang: ja
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
nav:
  - Home:  index.en.md
  - Overview:
    - Introduction: overview/index.en.md
    - Cover Pools:  overview/cover-pools.en.md
    - Limit Pools:  overview/limit-pools.en.md
    - Range Pools:  overview/range-pools.en.md
    - Glossary: overview/glossary.md
    #- Index: overview/indexes.md (need to add more terminology)
    # - Token Economy Overview:  introduction/token-economy-intro.en.md
  # - Protocol Guide:
  #   - Liquidity Types:
  #       - Liquidity Provider Overview:  protocol-guide/liquidity-providers/overview.en.md
  #       - Directional Liquidity:  protocol-guide/liquidity-providers/directional-liquidity.en.md
  #       - Cover Liquidity:  protocol-guide/liquidity-providers/single-sided.en.md
  #       - Limit Liquidity:  protocol-guide/liquidity-providers/directional-range-order.en.md
  #       - Range Liquidity:  protocol-guide/liquidity-providers/range-liquidity.en.md
  #   - Swaps:  protocol-guide/swaps.en.md
  #   - Mints:  protocol-guide/mints.en.md
  #   - Burns:  protocol-guide/burns.en.md
  #   - Fees:  protocol-guide/fees.en.md
  #   - Oracles:  protocol-guide/oracles.en.md
  - Tutorials:
#     - Basic Setup: tutorials/basic-setup.en.md
    - Swaps:  tutorials/how-to-swap.md
    - Cover:  tutorials/how-to-cover.md
    - Range:  tutorials/how-to-range.md
  - Smart Contracts:
      - Overview:  smart-contracts/overview.en.md
      - Cover:
          - CoverPoolFactory:  smart-contracts/cover/CoverPoolFactory.en.md
          - CoverPool:  smart-contracts/cover/CoverPool.en.md
      - Price:
          - LimitPoolFactory:  smart-contracts/limit/LimitPoolFactory.en.md
          - LimitPool:  smart-contracts/limit/LimitPool.en.md
      - Range: 
          - RangePoolFactory:  smart-contracts/range/RangePoolFactory.en.md
          - RangePool:  smart-contracts/range/RangePool.en.md
  - Whitepaper: whitepaper/index.en.md
  # - Token Economy:
  #     - Overview: token-economy/overview.en.md
  #     - Centripetal Mining: token-economy/centripetal-mining.en.md
  # - References:
  #   - Automated Market Makers: references/automated-market-makers.en.md
  #   - Limit Order Books: references/limit-order-books.en.md

#         - Single: tutorials/swaps/single.en.md
#         - Multicall: tutorials/swaps/multicall.en.md
#     - Liquidity: 
#         - Contract Setup: tutorials/liquidity/contract-setup.en.md
#         - Mint Position: tutorials/liquidity/mint-position.en.md
#         - Collect Fees: tutorials/liquidity/collect-fees.en.md
#         - Modify Liquidity: tutorials/liquidity/change-position.en.md
#     - Mining Incentives: tutorials/liquidity/mining-incentives.en.md
#     - Flash Swaps: 
#         - Contract Setup: tutorials/flash-swaps/contract-setup.en.md
#         - Execution: tutorials/flash-swaps/execution.en.md
#         - Callback: tutorials/flash-swaps/callback.en.md

theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font: false
  logo: assets/images/Logo-removebg.png
  favicon: assets/images/Logo-removebg.png
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - pymdownx.pathconverter:
      base_path: '' # default: ''
      relative_path: '' # default ''
      absolute: true    # default: false
      tags: 'a script img link object embed'
  - toc:
      permalink: True
  - abbr
  - admonition
  - tables
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.attr_list
  - md_in_html

plugins:
    - search
    # - redirects:
    #     redirect_maps:
    - i18n:
        default_language: en
        languages:
          en: english
          # ja: japanese
        material_alternate: false
    - glightbox
    # - macros:
    #     include_dir: site/content/docs/include
